# Generated by Django 3.1.2 on 2021-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('case_type', models.CharField(max_length=100, verbose_name='Тип дела')),
                ('paintiff', models.CharField(max_length=100, verbose_name='Истец')),
                ('defendant', models.CharField(max_length=100, verbose_name='Ответчик')),
                ('description', models.TextField(max_length=250, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
                ('service_type', models.CharField(max_length=100, verbose_name='Тип услуги')),
            ],
        ),
    ]
