# Generated by Django 3.1.2 on 2021-06-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcase',
            options={'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
    ]
